import { Build, Character, Gender, Height, SocialGroup } from "../types";

// Corrected characters array
const characters: Array<Character> = [
  {
    name: "Bartender",
    group: SocialGroup.Criminals,
    gender: Gender.Female,
    age: 40,
    build: Build.Large,
    height: Height.Average,
  },
  {
    name: "Fence",
    group: SocialGroup.Criminals,
    gender: Gender.Female,
    age: 60,
    build: Build.Medium,
    height: Height.Tall,
  },
  {
    name: "Informant",
    group: SocialGroup.Criminals,
    gender: Gender.Female,
    age: 20,
    build: Build.Small,
    height: Height.Short,
  },
  {
    name: "Bouncer",
    group: SocialGroup.Criminals,
    gender: Gender.Male,
    age: 20,
    build: Build.Large,
    height: Height.Tall,
  },
  {
    name: "Gangster",
    group: SocialGroup.Criminals,
    gender: Gender.Male,
    age: 40,
    build: Build.Medium,
    height: Height.Short,
  },
  {
    name: "Mafia Don",
    group: SocialGroup.Criminals,
    gender: Gender.Male,
    age: 60,
    build: Build.Small,
    height: Height.Average,
  },
  {
    name: "Bus Driver",
    group: SocialGroup.Labor,
    gender: Gender.Male,
    age: 60,
    build: Build.Large,
    height: Height.Short,
  },
  {
    name: "Waitress",
    group: SocialGroup.Labor,
    gender: Gender.Female,
    age: 40,
    build: Build.Medium,
    height: Height.Short,
  },
  {
    name: "Riveter",
    group: SocialGroup.Labor,
    gender: Gender.Female,
    age: 20,
    build: Build.Large,
    height: Height.Tall,
  },
  {
    name: "Librarian",
    group: SocialGroup.Labor,
    gender: Gender.Female,
    age: 60,
    build: Build.Small,
    height: Height.Average,
  },
  {
    name: "Ice Cream Man",
    group: SocialGroup.Labor,
    gender: Gender.Male,
    age: 20,
    build: Build.Medium,
    height: Height.Average,
  },
  {
    name: "Fireman",
    group: SocialGroup.Labor,
    gender: Gender.Male,
    age: 40,
    build: Build.Small,
    height: Height.Tall,
  },
  {
    name: "Musician",
    group: SocialGroup.Immigrants,
    gender: Gender.Male,
    age: 40,
    build: Build.Large,
    height: Height.Short,
  },
  {
    name: "Nun",
    group: SocialGroup.Immigrants,
    gender: Gender.Female,
    age: 60,
    build: Build.Large,
    height: Height.Tall,
  },
  {
    name: "Psychic",
    group: SocialGroup.Immigrants,
    gender: Gender.Female,
    age: 20,
    build: Build.Medium,
    height: Height.Short,
  },
  {
    name: "Professor",
    group: SocialGroup.Immigrants,
    gender: Gender.Male,
    age: 60,
    build: Build.Medium,
    height: Height.Average,
  },
  {
    name: "Navy Sailor",
    group: SocialGroup.Immigrants,
    gender: Gender.Male,
    age: 20,
    build: Build.Small,
    height: Height.Tall,
  },
  {
    name: "Cabin Crew",
    group: SocialGroup.Immigrants,
    gender: Gender.Female,
    age: 40,
    build: Build.Small,
    height: Height.Average,
  },
  {
    name: "Congressman",
    group: SocialGroup.Government,
    gender: Gender.Male,
    age: 60,
    build: Build.Large,
    height: Height.Average,
  },
  {
    name: "Secret agent",
    group: SocialGroup.Government,
    gender: Gender.Male,
    age: 20,
    build: Build.Medium,
    height: Height.Tall,
  },
  {
    name: "Mayor",
    group: SocialGroup.Government,
    gender: Gender.Male,
    age: 40,
    build: Build.Small,
    height: Height.Short,
  },
  {
    name: "Secretary",
    group: SocialGroup.Government,
    gender: Gender.Female,
    age: 20,
    build: Build.Large,
    height: Height.Short,
  },
  {
    name: "Ambassador",
    group: SocialGroup.Government,
    gender: Gender.Female,
    age: 40,
    build: Build.Medium,
    height: Height.Average,
  },
  {
    name: "Lobbyist",
    group: SocialGroup.Government,
    gender: Gender.Female,
    age: 60,
    build: Build.Small,
    height: Height.Tall,
  },
  {
    name: "Pharmacist",
    group: SocialGroup.Medicine,
    gender: Gender.Female,
    age: 20,
    build: Build.Large,
    height: Height.Average,
  },
  {
    name: "Veterinarian",
    group: SocialGroup.Medicine,
    gender: Gender.Male,
    age: 60,
    build: Build.Large,
    height: Height.Tall,
  },
  {
    name: "Nurse",
    group: SocialGroup.Medicine,
    gender: Gender.Female,
    age: 40,
    build: Build.Medium,
    height: Height.Tall,
  },
  {
    name: "Surgeon",
    group: SocialGroup.Medicine,
    gender: Gender.Male,
    age: 40,
    build: Build.Small,
    height: Height.Average,
  },
  {
    name: "Orderly",
    group: SocialGroup.Medicine,
    gender: Gender.Male,
    age: 20,
    build: Build.Medium,
    height: Height.Short,
  },
  {
    name: "Coroner",
    group: SocialGroup.Medicine,
    gender: Gender.Female,
    age: 60,
    build: Build.Small,
    height: Height.Short,
  },
  {
    name: "Judge",
    group: SocialGroup.Authority,
    gender: Gender.Female,
    age: 60,
    build: Build.Large,
    height: Height.Short,
  },
  {
    name: "Patrolman",
    group: SocialGroup.Authority,
    gender: Gender.Male,
    age: 20,
    build: Build.Small,
    height: Height.Short,
  },
  {
    name: "State Attorney",
    group: SocialGroup.Authority,
    gender: Gender.Male,
    age: 40,
    build: Build.Large,
    height: Height.Average,
  },
  {
    name: "Deputy",
    group: SocialGroup.Authority,
    gender: Gender.Female,
    age: 20,
    build: Build.Medium,
    height: Height.Average,
  },
  {
    name: "Lawyer",
    group: SocialGroup.Authority,
    gender: Gender.Female,
    age: 40,
    build: Build.Small,
    height: Height.Tall,
  },
  {
    name: "Dispatcher",
    group: SocialGroup.Authority,
    gender: Gender.Male,
    age: 60,
    build: Build.Medium,
    height: Height.Tall,
  },
  {
    name: "Beggar",
    group: SocialGroup.Outcasts,
    gender: Gender.Male,
    age: 60,
    build: Build.Small,
    height: Height.Short,
  },
  {
    name: "Veteran",
    group: SocialGroup.Outcasts,
    gender: Gender.Male,
    age: 40,
    build: Build.Medium,
    height: Height.Tall,
  },
  {
    name: "Greaser",
    group: SocialGroup.Outcasts,
    gender: Gender.Male,
    age: 20,
    build: Build.Large,
    height: Height.Average,
  },
  {
    name: "War Widow",
    group: SocialGroup.Outcasts,
    gender: Gender.Female,
    age: 40,
    build: Build.Large,
    height: Height.Short,
  },
  {
    name: "Cat Lady",
    group: SocialGroup.Outcasts,
    gender: Gender.Female,
    age: 60,
    build: Build.Medium,
    height: Height.Average,
  },
  {
    name: "Showgirl",
    group: SocialGroup.Outcasts,
    gender: Gender.Female,
    age: 20,
    build: Build.Small,
    height: Height.Tall,
  },
  {
    name: "Ballplayer",
    group: SocialGroup.JetSet,
    gender: Gender.Male,
    age: 20,
    build: Build.Large,
    height: Height.Short,
  },
  {
    name: "Benefactor",
    group: SocialGroup.JetSet,
    gender: Gender.Male,
    age: 40,
    build: Build.Medium,
    height: Height.Average,
  },
  {
    name: "Restaurateur",
    group: SocialGroup.JetSet,
    gender: Gender.Female,
    age: 60,
    build: Build.Medium,
    height: Height.Short,
  },
  {
    name: "Actress",
    group: SocialGroup.JetSet,
    gender: Gender.Female,
    age: 20,
    build: Build.Small,
    height: Height.Average,
  },
  {
    name: "Psychiatrist",
    group: SocialGroup.JetSet,
    gender: Gender.Male,
    age: 60,
    build: Build.Small,
    height: Height.Tall,
  },
  {
    name: "Artist",
    group: SocialGroup.JetSet,
    gender: Gender.Female,
    age: 40,
    build: Build.Large,
    height: Height.Tall,
  },
  {
    name: "Newscaster",
    group: SocialGroup.Press,
    gender: Gender.Male,
    age: 60,
    build: Build.Medium,
    height: Height.Short,
  },
  {
    name: "Paperboy",
    group: SocialGroup.Press,
    gender: Gender.Male,
    age: 20,
    build: Build.Small,
    height: Height.Average,
  },
  {
    name: "Photographer",
    group: SocialGroup.Press,
    gender: Gender.Male,
    age: 40,
    build: Build.Large,
    height: Height.Tall,
  },
  {
    name: "Reporter",
    group: SocialGroup.Press,
    gender: Gender.Female,
    age: 20,
    build: Build.Medium,
    height: Height.Tall,
  },
  {
    name: "Mailwoman",
    group: SocialGroup.Press,
    gender: Gender.Female,
    age: 40,
    build: Build.Small,
    height: Height.Short,
  },
  {
    name: "Editor",
    group: SocialGroup.Press,
    gender: Gender.Female,
    age: 60,
    build: Build.Large,
    height: Height.Average,
  },
];

export const useCharacters = () => {
  return characters;
};
