export enum SocialGroup {
  AUTHORITY = "AUTHORITY",
  MEDICINE = "MEDICINE",
  CRIMINALS = "CRIMINALS",
  PRESS = "PRESS",
  GOVERNMENT = "GOVERNMENT",
  JETSET = "JETSET",
  OUTCASTS = "OUTCASTS",
  LABOR = "LABOR",
  IMMIGRANTS = "IMMIGRANTS",
}
